import { expect, test } from '@playwright/test';
import { date, mockApi, toVenues, zones } from './fixtures';
test('uses the configured calendar, preserves selection across views and disables closed dates', async ({ page }) => {
  const state = await mockApi(page);
  state.calendarEnabled = true;
  await toVenues(page);
  await page.getByLabel('Zona', { exact: true }).selectOption(zones[0].id);
  await page.getByRole('radio', { name: /Polideportivo de prueba/ }).check();
  await page.getByRole('button', { name: 'Ver sede', exact: true }).click();
  await page.getByRole('button', { name: 'Ver disponibilidad' }).click();
  await expect(page.getByLabel('Mes del calendario')).toBeVisible();
  await page.getByLabel('Mes del calendario').fill(date.slice(0, 7));
  await page.locator('.rdp-day_button').filter({ hasText: /^1$/ }).click();
  await page.getByRole('radio', { name: '18:00 – 19:00' }).check();
  await page.getByRole('button', { name: 'Lista de horarios', exact: true }).click();
  await expect(page.getByLabel('Fecha', { exact: true })).toHaveValue(date);
  await expect(page.getByRole('radio', { name: '18:00 – 19:00' })).toBeChecked();
  state.unavailable = true;
  await page.getByRole('button', { name: 'Calendario', exact: true }).click();
  await expect(page.locator('.rdp-day_button').filter({ hasText: /^1$/ })).toBeDisabled();
  await page.getByRole('button', { name: 'Actualizar horarios' }).click();
  await expect(page.getByRole('button', { name: 'Revisar solicitud' })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('calendar.png'), fullPage: true });
});
